name: iraq_health_mobile
description: Iraq health patient app MVP
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.7
  dio: ^5.7.0
  flutter_local_notifications: ^17.2.4
  firebase_messaging: ^15.1.3
  intl: ^0.19.0

flutter:
  uses-material-design: true
  generate: true
